function cladeMap = getcladeMap(clademapfile)
    %map species/folder names to clades
    %save to cladeMap.mat
    if exist(clademapfile, 'file') == 2
        fprintf('Loading %s from %s\n',clademapfile,pwd)
        load(clademapfile);
    else
        cladeMap = containers.Map();
        cladeMap('nasuta') = {'albomicans', 'kepuluana', 'kohkoa',...
                              'nasuta', 'pallidifrons', 'pulaua',...
                              'salb', 'sbilim', 'sneonasuta', 'ssulf',...
                              'TaxonF', 'TaxonG', 'TaxonI', 'TaxonJ',...
                              'Cross1', 'Cross2', 'Cross3', 'Cross4',...
                              'Cross5', 'Cross6', 'Cross7', 'Cross8',...
                              'Cross15', 'Cross16', 'Cross17', 'Cross18',...
                              'Cross19', 'Cross20', 'Cross21', 'Cross22',...
                              'OtherF1'};
        cladeMap('ananassae') = {'ananassae', 'pallidosa', 'Cross10'};
        cladeMap('virilis') = {'americana', 'lummei', 'novomexicana', 'virilis',...
                               'Cross11', 'Cross12', 'Cross13', 'Cross14'};
        cladeMap('athabasca') = {'athabasca'};
        cladeMap('melanogaster') = {'melanogaster'};
        fprintf('Saving %s in %s\n',clademapfile,pwd)
        save(clademapfile,'cladeMap');
    end
end
