classdef ParametersClass
    properties
        outdir
        prevtempfile
        whichsignal
        segopts
        minpulse
        maxIPI
        ipiptl
        doplots
        remnoise
        numpulsemax
        diffThreshold
        pulsetrainmax
        sigmaThreshold
        filtcut
        fs
        femalecut
        baseline_quantile
        template_pca_dimension
        isshort
        domalefemale
        plotanalyzerdir
        analyzerdir
        segmenterdir
        chronuxdir
        butterdir
    end
end
